### ISSUE TITLE
negative: When enabled, it affects all newly created windows

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz-plugins-main#24] opened 2017-01-23 23:10 UTC
I don't think this is intended to be the default behavior. If it *is* intended to be the default behavior, this turns into a feature request for an option for it to not work that way. :)

**Comment by ethus3h** [comment] 2017-01-23 23:21
Oh, I see, that was an intentional change in d0da0354c31a4f9443fd5c81da29ceae8f68bd65. I still don't think this should be default, though.

**Comment by ethus3h** [comment] 2017-01-25 02:49
https://github.com/compiz-reloaded/compiz-plugins-main/pull/25 should fix this.

**Comment by ethus3h** [comment] 2017-04-12 02:52
For the record, I think now that basically everything I wrote in this issue was wrong. I just had to make the "Negative windows" field not match anything.

**Comment by moontide** [comment] 2017-04-24 10:35
just upgraded to 0.8.14-1.fc26, this "automatically enabled" bug drive me crazy.

it's better to add an option (checkbox) called "automatically enabled" to do this if someone really need this feature/bug.

**Comment by ethus3h** [comment] 2017-04-24 15:50
@moontide: For me, it was fixed by clearing the "Negative windows" field so it didn't match anything (just delete the contents of it). That way, only windows I manually toggled were negative. Hope this helps!

**Comment by soreau** [comment] 2017-04-24 17:25
I didn't notice this until more recently, caused by [d0da0354](https://github.com/compiz-reloaded/compiz-plugins-main/commit/d0da0354c31a4f9443fd5c81da29ceae8f68bd65) it is certainly buggy. I did a minor overhaul but it needs testing, if anyone would like to try it: http://sprunge.us/UeAe

**Comment by ethus3h** [comment] 2017-04-24 18:10
The patch you provided seems to work, thanks! :D.

The only slight possible problem I note with it is that when Auto-Toggle Matched Windows is un-checked, all windows that were matched remain negated (and thus need to be manually un-toggled).

**Comment by soreau** [comment] 2017-04-24 18:12
Yes, and when the match field is changed, if adding an inverted match, there is no effect. Respinning another patch..

**Comment by soreau** [comment] 2017-04-24 19:14
Here's a new version of the patch http://sprunge.us/fLIY In this version, if the option is enabled and toggle screen is used to disable negation, newly created windows won't be negated. It also fixes updating windows when the match field is changed and I'm hoping, the bug @ethus3h mentioned with the previous patch.

**Comment by moontide** [comment] 2017-04-25 01:51
@ethus3h 
> @moontide: For me, it was fixed by clearing the "Negative windows" field so it didn't match anything (just delete the contents of it). That way, only windows I manually toggled were negative. Hope this helps!

Thanks, that what I did exactly after read your 4th post.
But when click the "reset" button, it will bring it ('`any`') back.

**Comment by ethus3h** [comment] 2017-04-25 02:05
@moontide: ...then ... don't click the reset button?

**Comment by soreau** [comment] 2017-04-25 15:53
This should be fixed by [10c31d45](https://github.com/compiz-reloaded/compiz-plugins-main/commit/10c31d456640a86b50448a0b09a7220b1ba737bd).

**Closed by soreau** 2017-04-25 15:53 UTC
Labels: bug
